### Spring properties
# Service registers under this name
spring:
  application:
    name: evento-microservice

# Discovery Server Access
# URL de acceso al servicio de Eureka
eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:1111/eureka/

# HTTP Server (Tomcat) Port
# Puerto de escucha. Es necesario pq todos los procesos a ejecutar que usan Tomcat no pueden usar a la vez el 8080
server: 
  port: 2222
# Disable Spring Boot's "Whitelabel" default error page, so we can use our own  
  error:
    whitelabel:
      enabled: false 